soundCategory: RECORDS

trident:
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 1
    velocity : 1.75
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 2
    velocity : 2.6
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 3
    velocity : 3.5
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 4
    velocity : 6.5

